spring:
  config:
    import: optional:file:.env[.properties]


jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: 3600000
  refresh-token-expire-time: 5184000000

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    token_uri: https://oauth2.googleapis.com/token
    user-info-url: https://www.googleapis.com/oauth2/v3/userinfo
    redirect-uri: http://localhost:8080/login/oauth2/code/google
    delete-account-url: http://localhost:8080

