spring:
  config:
    import: optional:file:.env[.properties]


jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: 3600000
  refresh-token-expire-time: 5184000000

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    token-uri: https://oauth2.googleapis.com/token
    user-info-url: https://www.googleapis.com/oauth2/v3/userinfo
    redirect-uri: http://localhost:8080/login/oauth2/code/google
    delete-account-url: ${GOOGLE_DELETE_ACCOUNT_URL}

  apple:
    ios:
      client-id: ${APPLE_IOS_CLIENT_ID}
      team-id: ${APPLE_IOS_TEAM_ID}
      key-id: ${APPLE_IOS_KEY_ID}
      private-key: ${APPLE_IOS_PRIVATE_KEY}
      token-url: ${APPLE_IOS_TOKEN_URL}
      delete-account-url: ${APPLE_IOS_DELETE_ACCOUNT_URL}

  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-url: https://kapi.kakao.com/v2/user/me
    redirect-uri: http://localhost:8080/login/oauth2/code/kakao


