spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${profile}
    include: oauth
  datasource:
    hikari:
      maximum-pool-size: 15

---
spring.config.active.on-profile: local

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: test
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


